# Dependabot configuration file
# See https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  # Enable version updates for npm
  - package-ecosystem: "npm"
    # Look for package.json and package-lock.json files in the root directory
    directory: "/"
    # Check for updates once a week (on Monday)
    schedule:
      interval: "weekly"
      day: "monday"
    # Group all updates together
    groups:
      development-dependencies:
        dependency-type: "development"
      production-dependencies:
        dependency-type: "production"
    # Specify labels for npm pull requests
    labels:
      - "npm"
      - "dependencies"
    # Set a limit on the number of open pull requests for npm dependencies
    open-pull-requests-limit: 10
    # Allow up to 5 pull requests for security updates
    security-updates-limit: 5
    # Specify the version update strategy
    versioning-strategy: "auto"
    # Ignore certain dependencies
    ignore:
      # Ignore major version updates for these packages
      - dependency-name: "@types/*"
        update-types: ["version-update:semver-major"]

  # Enable version updates for GitHub Actions
  - package-ecosystem: "github-actions"
    # Look for GitHub Actions workflow files in the .github/workflows directory
    directory: "/"
    # Check for updates once a week
    schedule:
      interval: "weekly"
    # Specify labels for GitHub Actions pull requests
    labels:
      - "github-actions"
      - "dependencies"
    # Set a limit on the number of open pull requests for GitHub Actions
    open-pull-requests-limit: 5
    
  # Enable version updates for Docker
  - package-ecosystem: "docker"
    # Look for a Dockerfile in the root directory
    directory: "/"
    # Check for updates once a month
    schedule:
      interval: "monthly"
    # Specify labels for Docker pull requests
    labels:
      - "docker"
      - "dependencies"
    # Set a limit on the number of open pull requests for Docker
    open-pull-requests-limit: 3